# ğŸ”— é“¾æ¥ï¼š
# æºæ–‡ä»¶ï¼šhttps://github.com/obytes/react-native-template-obytes/blob/master/.github/workflows/e2e-android.yml
# ç«¯åˆ°ç«¯æµ‹è¯•ï¼šhttps://starter.obytes.com/testing/end-to-end-testing/

# âœï¸ æè¿°ï¼š
# æ­¤å·¥ä½œæµç”¨äºä½¿ç”¨ Maestro Cloud åœ¨ Android ä¸Šè¿è¡Œç«¯åˆ°ç«¯æµ‹è¯•ã€‚
# ä½œä¸ºç¬¬ä¸€æ­¥ï¼Œå®ƒå°†ä½¿ç”¨ Gradle æ„å»ºç”Ÿæˆæµ‹è¯• APKï¼Œç„¶åè§¦å‘ Maestro Cloud åœ¨ç”Ÿæˆçš„ APK ä¸Šè¿è¡Œæµ‹è¯•ã€‚
# æ­¤å·¥ä½œæµå°†åœ¨å¸¦æœ‰ "android-test-maestro-cloud" æ ‡ç­¾çš„æ‹‰å–è¯·æ±‚ï¼ˆPRï¼‰ä¸Šè§¦å‘ï¼Œæˆ–å¯ä»¥ä» Actions é€‰é¡¹å¡æ‰‹åŠ¨è§¦å‘ã€‚

# ğŸš¨ éœ€è¦ GITHUB å¯†é’¥ï¼š
# MAESTRO_CLOUD_API_KEYï¼šMaestro Cloud çš„ API å¯†é’¥ã€‚æ‚¨å¯ä»¥ä» https://cloud.mobile.dev/ci-integration/github-actions#add-your-api-key-secret è·å–å®ƒ

name: E2E Tests Android (Maestro Cloud)

on:
  workflow_dispatch:
  pull_request:
    branches: [main, master]

jobs:
  generate-and-test-apk:
    if: github.event_name != 'pull_request' || ( github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'android-test-maestro-cloud'))
    name: Generate and Test Test APK (Maestro Cloud)
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¦ Checkout project repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ğŸ“¦ Setup Node + PNPM + install deps
        uses: ./.github/actions/setup-node-pnpm-install

      - name: ğŸ“¦ Set Up JDK + Generate Test APK
        uses: ./.github/actions/setup-jdk-generate-apk
        with:
          APP_ENV: staging

      - name: Upload Test APK
        uses: actions/upload-artifact@v3
        with:
          name: test-apk
          path: ./android/app/build/outputs/apk/release/app-release.apk

      - name: ğŸ“± Run E2E Tests with Maestro Cloud
        uses: mobile-dev-inc/action-maestro-cloud@v1.4.1
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: ./android/app/build/outputs/apk/release/app-release.apk
          env: |
            APP_ID=com.obytes.staging
