# ğŸ”— é“¾æ¥ï¼š
# æºæ–‡ä»¶ï¼šhttps://github.com/obytes/react-native-template-obytes/blob/master/.github/workflows/e2e-android.yml
# ç«¯åˆ°ç«¯æµ‹è¯•ï¼šhttps://starter.obytes.com/testing/end-to-end-testing/

# âœï¸ æè¿°ï¼š
# æ­¤å·¥ä½œæµç”¨äºä½¿ç”¨ Maestro åœ¨ Android ä¸Šè¿è¡Œç«¯åˆ°ç«¯æµ‹è¯•ã€‚
# ä½œä¸ºç¬¬ä¸€æ­¥ï¼Œå®ƒå°†ä½¿ç”¨ Gradle æ„å»ºç”Ÿæˆæµ‹è¯• APKï¼Œç„¶åå°†å…¶ä½œä¸ºå·¥ä»¶ä¸Šä¼ ã€‚
# å°†å¯åŠ¨ä¸€ä¸ªæ–°ä½œä¸šæ¥ä½¿ç”¨å‰ä¸€ä¸ªä½œä¸šä¸­ç”Ÿæˆçš„æµ‹è¯• APK è¿è¡Œæµ‹è¯•ã€‚
# ä¸ºäº†æµ‹è¯•åº”ç”¨ï¼Œæˆ‘ä»¬ä½¿ç”¨ `reactivecircus/android-emulator-runner` åŠ¨ä½œè®¾ç½® Android æ¨¡æ‹Ÿå™¨ã€‚æ­¤è¿è¡Œå™¨éœ€è¦ macOS ä½œä¸ºè¿è¡Œå™¨çš„æ“ä½œç³»ç»Ÿã€‚
# æ­¤å·¥ä½œæµå°†åœ¨å¸¦æœ‰ "android-test-github" æ ‡ç­¾çš„æ‹‰å–è¯·æ±‚ï¼ˆPRï¼‰ä¸Šè§¦å‘ï¼Œæˆ–å¯ä»¥ä» Actions é€‰é¡¹å¡æ‰‹åŠ¨è§¦å‘ã€‚
#

# ğŸš¨ éœ€è¦ GITHUB å¯†é’¥ï¼šæ— 

name: E2E Tests Android (Maestro + Github Action)

on:
  workflow_dispatch:
  pull_request:
    branches: [main, master]

jobs:
  generate-test-apk:
    if: github.event_name != 'pull_request' || ( github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'android-test-github'))
    name: Generate Test APK (Gradle)
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¦ Checkout project repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ğŸ“¦ Setup Node + PNPM + install deps
        uses: ./.github/actions/setup-node-pnpm-install

      - name: ğŸ“¦ Set Up JDK + Generate Test APK
        uses: ./.github/actions/setup-jdk-generate-apk
        with:
          APP_ENV: staging

      - name: Upload Test APK
        uses: actions/upload-artifact@v3
        with:
          name: test-apk
          path: ./android/app/build/outputs/apk/release/app-release.apk

  test-android:
    name: Run Android E2E Tests (Maestro + Github Action)
    needs: generate-test-apk
    runs-on: macOS-latest

    steps:
      - name: ğŸ“¦ Checkout project repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ğŸ“¦ Install Maestro
        run: npm run install-maestro ## We use npm because we don't need to install deps again

      - name: Download Test APK
        uses: actions/download-artifact@v3
        with:
          name: test-apk
          path: ${{ github.workspace }}

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-cache

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          cores: 2
          ram-size: 4096M
          profile: Nexus 6
          script: echo "Generated AVD snapshot for caching."

      - name: Run tests with Maestro
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          cores: 2
          ram-size: 4096M
          profile: Nexus 6
          script: |
            adb install "${{ github.workspace }}/app-release.apk"
            $HOME/.maestro/bin/maestro test .maestro/ --env=APP_ID=com.obytes.staging  --format junit

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: e2e-test-logs
          path: ~/.maestro/tests/**/*

      - name: Store tests result
        uses: actions/upload-artifact@v3
        with:
          name: e2e_android_report
          path: |
            report.xml
